[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
ENVIRONMENT = "production"